# Generated by Django 5.1.2 on 2024-10-12 04:17

import class_manager.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('visibility', models.CharField(choices=class_manager.models.get_visibility_choices, max_length=80)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='class_manager.baseattribute')),
                ('arguments', models.CharField(blank=True, max_length=255, null=True)),
                ('return_type', models.CharField(blank=True, max_length=160, null=True)),
            ],
            bases=('class_manager.baseattribute',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='class_manager.baseattribute')),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('class_manager.baseattribute',),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='baseattribute',
            name='class_assoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_manager.class'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='#1d4ed8', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_manager.module'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_manager.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_manager.project')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='projects',
            field=models.ManyToManyField(through='class_manager.ProjectModule', to='class_manager.project'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_model', to='class_manager.class')),
                ('to_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_model', to='class_manager.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='relationships',
            field=models.ManyToManyField(through='class_manager.Relationship', to='class_manager.class'),
        ),
        migrations.AddConstraint(
            model_name='projectmodule',
            constraint=models.UniqueConstraint(fields=('project', 'module'), name='unique_project_module'),
        ),
    ]
