# Generated by Django 5.1.2 on 2024-10-12 23:43

import class_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=class_manager.models.get_relationship_type_choices, default='none', max_length=80),
            preserve_default=False,
        ),
    ]
