# Generated by Django 5.1.2 on 2024-11-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_manager', '0002_relationship_relationship_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name="relationship",
            old_name="from_model",
            new_name="from_class"
        ),
        migrations.RenameField(
            model_name="relationship",
            old_name="to_model",
            new_name="to_class"
        )
    ]
