# Generated by Django 5.1.2 on 2024-11-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_manager', '0003_auto_20241107_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_class', to='class_manager.class'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_class', to='class_manager.class'),
        ),
    ]
