# Generated by Django 5.1.2 on 2024-11-19 04:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_manager', '0005_alter_baseattribute_class_assoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#1d4ed8', help_text='The color of class diagrams in this module on UML diagrams.', image_field=None, max_length=25, samples=[('#000000', 'Black'), ('#334155', 'Slate'), ('#44403c', 'Stone'), ('#854d0e', 'Brown'), ('#dc2626', 'Red'), ('#db2777', 'Pink'), ('#e11d48', 'Rose'), ('#ea580c', 'Orange'), ('#d97706', 'Amber'), ('#fcdb03', 'Yellow'), ('#65a30d', 'Lime'), ('#15803d', 'Green'), ('#0d9488', 'Teal'), ('#0284c7', 'Sky'), ('#1d4ed8', 'Blue'), ('#4338ca', 'Indigo'), ('#6d28d9', 'Violet'), ('#c026d3', 'Fuchsia'), ('#ffffff', 'White')]),
        ),
    ]
