# Generated by Django 5.1.2 on 2024-11-20 16:42

import class_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_manager', '0008_baseattribute_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseattribute',
            name='visibility',
            field=models.CharField(blank=True, choices=class_manager.models.get_visibility_choices, help_text='Public (+): visible to any object that can view the class\n\nProtected (#): visible to objects that can view the class and are derived from the class\n\nPrivate (-): visibile only within the class and its instances', max_length=80, null=True),
        ),
    ]
